district09/php_package_qa-drupal

README.md
composer.json
configs/grumphp-extension.yml
configs/grumphp-site.yml

The namespace of the project has changed but the references are still pointing to the old namespace.

Rename package to digipolisgent/qa-drupal (2.x branch)

---

README.md
composer.json
configs/grumphp-extension.yml
configs/grumphp-site.yml
configs/phpcs.xml
configs/phpmd.xml
configs/phpstan.neon
configs/phpunit-extension.xml
src/Behat/Context/AccessContext.php
src/Behat/Context/DebugContext.php
src/Behat/Context/SelectorContext.php
src/Behat/Context/UriContext.php
src/GrumPHP/EventListener/TaskEventListener.php
src/PHPUnit/Extension/bootstrap.php
src/PHPUnit/TestSuites/FunctionalJavascriptTestSuite.php
src/PHPUnit/TestSuites/FunctionalTestSuite.php
src/PHPUnit/TestSuites/KernelTestSuite.php
src/PHPUnit/TestSuites/TestSuiteBase.php
src/PHPUnit/TestSuites/UnitTestSuite.php

- Fixed PHP CodeSniffer rules so they follow drupal.org.
- Fixed PHP Mess Detector rules so they have proper defaults and support drupal codebase.
- Fixed timeout issues when running GrumPHP tasks on large code base.
- Added support to run PHPUnit tests without the need of an external Drupal directory.

Fix code standards and run extension tests in isolation

---

composer.json
configs/phpmd.xml

- Add Drupal 9.0 support.
- Allow short `$id` variable and `id()` method name.

Add Drupal 9 support

---

composer.json

Drupal 9.1 requires PHPUnit 9.
See https://github.com/drupal/core-dev/blob/9.1.x/composer.json
See https://www.drupal.org/node/3176567

Add support for Drupal 9.1

---

.editorconfig
CHANGELOG.md
composer.json
configs/grumphp-extension.yml
configs/grumphp-site.yml
configs/phpstan-extension.neon
configs/phpunit-extension.xml
configs/phpunit-site.xml
src/GrumPHP/ConfigFileMerger.php
src/GrumPHP/EventListener/ConsoleEventListener.php
src/GrumPHP/EventListener/TaskEventListener.php
src/GrumPHP/TransactionalFilesystem.php
src/PHPUnit/Extension/bootstrap.php

The PHPStan Drupal plugin to detect deprecations requires a Drupal root.
The implemented pre task event handler adds the missing files so PHPStan "sees" a Drupal installation.
Added the TransactionalFileSystem that automatically cleans up all directories and files created during a task run (merged from 1.3.x).
Extracted the config file merging functionality to a dedicated class.
Deprecations are already detected by PHPStan, no need to detect these also during PHPUnit runs.
This task is a wrapper around a composer plugin for tidying up the file composer.json.
Added using the use the `Drupal\TestTools\PhpUnitCompatibility\PhpUnit8\ClassWriter` to check and
fix incompatible `setUp()` methods in Drupal Core.
See https://www.drupal.org/node/3114041.

Fix PHPStan & PHPUnit integration

---

CHANGELOG.md
configs/phpunit-extension.xml

We allow 2 deprecations due to Drupal 8.x deprecated usage of Symfony
components. Drupal 9.x should only have 1.

Fix allowed number of deprecation errors

---

composer.json
configs/grumphp-extension.yml
configs/grumphp-site.yml
src/Digipolisgent/QA/Drupal/Twigcs/Ruleset/Twig.php

See https://github.com/friendsoftwig/twigcs & https://github.com/phpro/grumphp/blob/master/doc/tasks/twigcs.md
[x] nice to have: https://github.com/NielsdeBlaauw/twigcs-a11y/pull/2
[ ] detect missing comma: https://github.com/friendsoftwig/twigcs/issues/167

TTWEBTAKEN-85: Add Twig linter.

---

composer.json
configs/grumphp-extension.yml
configs/grumphp-site.yml

The SensioLabs Security Checker API is abandoned.
```
securitychecker
===============
The securitychecker task is discontinued by SensioLabs.
Please consider switching to one of the following tasks instead:
- securitychecker_enlightn (https://github.com/phpro/grumphp/blob/master/doc/tasks/securitychecker/enlightn.md)
- securitychecker_local (https://github.com/phpro/grumphp/blob/master/doc/tasks/securitychecker/local.md)
- securitychecker_symfony (https://github.com/phpro/grumphp/blob/master/doc/tasks/securitychecker/symfony.md)
```
See https://github.com/phpro/grumphp/blob/master/doc/tasks/securitychecker.md
Replaced by https://github.com/phpro/grumphp/blob/master/doc/tasks/securitychecker/enlightn.md
```
GrumPHP is sniffing your code!
Running tasks with priority 0! …
```

Replace deprecated security-checker

---

composer.json

The symfony security checker is no longer supported.

Update minimal requirement for grumphp

---

configs/phpstan.neon

Configuration parameters excludes_analyse and excludePaths cannot be used at the same time.

Depracate excludes_analyse

---

configs/grumphp-site.yml

They often contain schema definitions in hook_schema _and_ in the update hook 
where the table was added, triggering phpcpd.

Add .install files to the ignore list of phpcpd

---

configs/grumphp-site.yml

It was added to the exclude list in the previous version, but it would appear 
that wasn't enough.

Remove the install suffix for phpcpd

---

CHANGELOG.md
README.md
configs/phpcs.xml

Something has changed in the CodeClimate platform (update of the used
PHP version?) that breaks the CodeClimate tests.
The first error is:
> PHP Deprecated:  Array and string offset access syntax with curly
> braces is deprecated in
> /usr/src/app/vendor/squizlabs/php_codesniffer/CodeSniffer.php
> on line x
```
CodeClimate uses by default version 2.8.x
(see https://docs.codeclimate.com/docs/phpcodesniffer). The 3.6.x
version is available using the "beta channel".
Fix this by adding the channel to your `.codeclimate.yml` file:
```yaml
plugins:
phpcodesniffer:
enabled: true
channel: beta
config:
standard: ".phpcs.xml"
```
The `.phpcs.xml` file is fetched from this repository and added to the
project before CodeClimate starts running the checks and plugins. A new
error emerges after changing …
```

Fix failing CodeClimate checks

---

README.md
composer.json
configs/phpcs.xml

Needs a grumphp plugin to pass in the checks against a specific PHP version by adding `--runtime-set testVersion 8.1` to the command line command
See
- https://github.com/wunderio/grumphp-php-compatibility
- https://github.com/wunderio/code-quality/blob/master/src/Task/PhpCompatibility/PhpCompatibilityTask.php

Add php compatibility checker

---

.travis.yml
composer.json

- Bumped minimal Drupal version to ^9.3.
- Add travis build to validate if it can be installed with all supported
PHP and Drupal core versions.

PHP-81: Add travis build

---

CHANGELOG.md
configs/phpunit-extension.xml
configs/phpunit-site.xml

This excludes manually crafted mocks as long as their file name ends with:
- Spy.php
- Stub.php

Add excluding hand-crafted mocks from coverage reports.

---

CHANGELOG.md
configs/phpunit-site.xml

Some node modules have PHP in them ¯\_(ツ)_/¯.
We add the custom theme source directory (who only contains scss, js & node modules) to the excluded directories.
Example of node module with PHP: https://github.com/WebReflection/flatted/tree/main/php

Add exclude node modules from PHPUnit

---

composer.json
configs/behat.yml

Use the browserkit_http driver instead og the goutte driver. See: https://github.com/jhedstrom/drupalextension/commit/2ab66a7eae53ae4e1e5824edaa72e98039b084db

BEHAT-UPDATE: Change to browserkit instead of goutte

---

CHANGELOG.md
composer.json
configs/phpunit-site.xml

This unfortunately means dropping support for previous Drupal versions. A line was added to Drupal's phpunit boostrap file, causing the old config to break:
https://git.drupalcode.org/project/drupal/-/blob/10.2.0/core/tests/bootstrap.php#L185

Add support for Drupal 10.2

---

CHANGELOG.md
configs/grumphp-site.yml

We don't care what is inside the node_modules directory.
Some node modules can have php files in them for whatever reason. We should not check the code within the node_modules directory as it is not ours.

Add custom theme(s) node_modules to the phpcpd exclude patterns

---

CHANGELOG.md
configs/phpunit-site.xml

A line was removed from the Drupal's phpunit boostrap file, causing the old config to break:
https://git.drupalcode.org/project/drupal/-/blob/10.2.0/core/tests/bootstrap.php#L185

Fix phpunit not finding file

---

composer.json
src/Twigcs/Ruleset/Twig.php

Since the old twigcs-a11y module is not symfony 7 proof and no longer maintained it's better to just use freiendsoftwig/twigcs.
Also see:
https://github.com/district09/php_package_qa-drupal/issues/42

Add twigcs because this was removed for the D11 upgrade

---

configs/phpunit-extension.xml
configs/phpunit-site.xml

Update the PHPUnit configuration files to:
- Support version 10 & 11.
- Fix deprecations.
- Add more verbose output on test errors/warnings/notices.

Update PhpUnit configuration

---

configs/phpunit-extension.xml

Some modules are a folder containing multiple submodules who are not grouped in a `modules` directory. Those locations are added to the PHPUnit configuration.

Add support for module collections
